CREATE DATABASE a3psc;

USE a3psc;

CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
idade INT NOT NULL,
sexo ENUM('M', 'F', 'O') NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
tipo ENUM('ADMIN', 'COMUM') NOT NULL
);

CREATE TABLE eventos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
descricao TEXT NOT NULL,
dataInicio DATETIME NOT NULL,
dataTermino DATETIME NOT NULL
);
